name: AWS CodeBuild run build

on:
  push:
    branches: [ master ]
    tags: [v*]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Run CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1.0.3
      with:
        project-name: soyal-middleware
